package secretAgent.io.map.orig.generator

/**
 * Object generated by object generator.
 *
 * @author Ondrej Milenovsky
 */
class GeneratedObject(val type: GeneratedType, val `object`: Any)

/**
 * Type of generated object
 *
 * @author Ondrej Milenovsky
 */
enum class GeneratedType {
    BACKGROUND,
    FOREGROUND,
    ENTITY
}