package cz.wa.secretagent.io.map.orig.generator;

/**
 * Object generated by object generator. 
 * 
 * @author Ondrej Milenovsky
 */
public class GeneratedObject {
    private final GeneratedType type;
    private final Object object;

    public GeneratedObject(GeneratedType type, Object object) {
        this.type = type;
        this.object = object;
    }

    public GeneratedType getType() {
        return type;
    }

    public Object getObject() {
        return object;
    }

}
